### PR TITLE
Hackit

### PR DESCRIPTION
**Pull request by elijahnavarro**
Added count variable to track number of moves made.

### CODE REVIEW

**Comment by elijahnavarro** [comment]
@ishanbagchi here is a PR for your review.

**Comment by ishanbagchi** [comment]
@elijahnavarro are you from SIT and contributing for Hack It feast?

**Comment by elijahnavarro** [comment]
@ishanbagchi I am contributing for Hack-it fest, yes.

**Comment by ishanbagchi** [comment]
@elijahnavarro Are you from SIT? If yes what is your name?

**Comment by elijahnavarro** [comment]
@ishanbagchi No - I do not know what SIT is.

**Comment by ishanbagchi** [comment]
@elijahnavarro sorry, Hack It is only for the students of Siliguri Institute Of Technology (SIT). 
However, I'll merge the pr after the completion ends. Sorry for the inconvenience.

**Comment by elijahnavarro** [comment]
@ishanbagchi Ah okay I see, thank you!

**Pull request merged**
